default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: epb_test_rails_development

test:
  <<: *default
  database: epb_test_rails_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
